apiVersion: v1
kind: Pod
metadata:
  name: med-pod
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.labels.app }}

spec:
  containers:
    - name: {{ .Values.container.name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

      ports:
        - containerPort: {{ .Values.container.port }}

      envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }}
        - secretRef:
            name: {{ .Values.secret.name }}

      volumeMounts:
        - name: config-volume
          mountPath: /app/config

        - name: temp-volume
          mountPath: /app/temp

  volumes:
    - name: config-volume
      configMap:
        name: {{ .Values.configMap.name }}

    - name: temp-volume
      emptyDir: {}
